name: Build & Publish (gh-pages)

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  repository_dispatch:
    types: [ site-template-updated ] 

jobs:
  call-central:
    uses: Academic-Codex/academic-codex.github.io/.github/workflows/build-template-site.yml@main
    with:
      execute: "false"
      placeholders_path: ".github/placeholders"
      template_repo: "Academic-Codex/academic-codex.github.io"
    secrets: inherit